'use client'

// Корпоративная версия (TEAM) — Phase 1. Deploys to /team/invite (see
// scripts/deploy-frontend.js — follows the same "-server.tsx is the live
// file, no stale non-suffixed twin" convention as dashboard-server.tsx /
// admin-server.tsx / team-server.tsx in this same directory).
//
// Handles the link generated by lib/email.js's sendOrgInviteEmail():
//   `${FRONTEND_URL}/team/invite?token=...`
// and calls POST /api/org/invites/:token/accept (org-routes.js), which
// requires the caller to already be authenticated with an account whose
// email matches the invite (see that route's comment for the rationale).
//
// Deliberate scope limit: login.tsx / register.tsx don't support a
// post-auth redirect target in this codebase, and adding one is out of
// scope for this Phase 1 pass (it would touch shared auth pages used by
// every other flow). So when the visitor isn't authenticated yet, we just
// point them at login/register and ask them to re-open this same email
// link afterward — the token in the URL is stable and single-use only
// once actually accepted, so re-visiting before acceptance is harmless.

import { useState, useEffect, Suspense } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import Link from 'next/link'
import { useAuthStore } from '@/store/authStore'
import { api } from '@/lib/api'

const ROLE_LABELS: Record<string, string> = { OWNER: 'владелец', ADMIN: 'администратор', MEMBER: 'участник' }

export default function TeamInvitePage() {
  return (
    <Suspense fallback={null}>
      <TeamInvitePageInner />
    </Suspense>
  )
}

function TeamInvitePageInner() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const token = searchParams.get('token') || ''
  const { user, _hasHydrated, setUser } = useAuthStore()

  const [status, setStatus] = useState<'idle' | 'accepting' | 'done' | 'error'>('idle')
  const [error, setError] = useState('')
  const [result, setResult] = useState<{ orgName: string; role: string } | null>(null)

  const handleAccept = async () => {
    setStatus('accepting')
    setError('')
    try {
      const { data } = await api.post(`/api/org/invites/${encodeURIComponent(token)}/accept`)
      setResult({ orgName: data.data.orgName, role: data.data.role })
      setStatus('done')
      // Refresh /me so authStore.user.orgSummary reflects the new membership
      // immediately (same pattern as team-server.tsx's refreshOrg()) —
      // otherwise the dashboard nav would still show "Создать команду"
      // until the next full page load re-hydrates from /me.
      try {
        const me = await api.get('/api/auth/me')
        setUser(me.data.user)
      } catch { /* non-fatal — next navigation will pick it up */ }
    } catch (err: any) {
      setError(err.response?.data?.error || 'Не удалось принять приглашение')
      setStatus('error')
    }
  }

  useEffect(() => {
    if (!token) {
      setError('Ссылка-приглашение повреждена: отсутствует токен')
      setStatus('error')
    }
  }, [token])

  if (!_hasHydrated) {
    return <Spinner />
  }

  return (
    <>
      <GlobalStyle />
      <div className="invite-page">
        <div className="invite-card">
          <div className="invite-icon"><IcoTeam /></div>

          {!user && status !== 'error' && (
            <>
              <h1>Приглашение в команду</h1>
              <p className="invite-sub">
                Чтобы принять приглашение, сначала войдите в аккаунт Centrio (или создайте новый на тот же email,
                на который пришло письмо), затем откройте эту ссылку из письма ещё раз.
              </p>
              <div className="invite-actions">
                <Link href="/auth/login" className="btn-primary">Войти</Link>
                <Link href="/auth/register" className="btn-ghost">Создать аккаунт</Link>
              </div>
            </>
          )}

          {user && status === 'idle' && token && (
            <>
              <h1>Приглашение в команду</h1>
              <p className="invite-sub">
                Вы вошли как <b>{user.email}</b>. Если это письмо адресовано другому email — войдите под тем аккаунтом
                и откройте ссылку заново.
              </p>
              <button className="btn-primary" onClick={handleAccept}>Принять приглашение</button>
            </>
          )}

          {status === 'accepting' && (
            <>
              <h1>Принимаем приглашение…</h1>
              <div className="mini-spinner" />
            </>
          )}

          {status === 'done' && result && (
            <>
              <h1>Готово</h1>
              <p className="invite-sub">
                Вы присоединились к команде «{result.orgName}» как {ROLE_LABELS[result.role] || result.role}.
              </p>
              <button className="btn-primary" onClick={() => router.push('/team')}>Перейти в команду</button>
            </>
          )}

          {status === 'error' && (
            <>
              <h1>Не получилось</h1>
              <p className="invite-sub invite-error">{error}</p>
              <button className="btn-ghost" onClick={() => router.push('/dashboard')}>В личный кабинет</button>
            </>
          )}
        </div>
      </div>
    </>
  )
}

function Spinner() {
  return (
    <div style={{ minHeight: '100vh', background: '#0b0a08', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <div style={{ width: 38, height: 38, border: '3px solid rgba(6,182,212,0.25)', borderTopColor: '#06b6d4', borderRadius: '50%', animation: 'spin .8s linear infinite' }} />
      <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
    </div>
  )
}

const IcoTeam = () => (
  <svg width="28" height="28" viewBox="0 0 24 24" fill="none">
    <circle cx="9" cy="8" r="3.2" stroke="currentColor" strokeWidth="1.6" />
    <path d="M2.5 20c0-3.6 2.9-6 6.5-6s6.5 2.4 6.5 6" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" />
    <path d="M16 5.2c1.5.3 2.6 1.6 2.6 3.1 0 1.5-1.1 2.8-2.6 3.1" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" />
    <path d="M17.5 14.3c2.1.6 3.5 2.4 3.5 4.7" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" />
  </svg>
)

function GlobalStyle() {
  return (
    <style>{`
      :root { color-scheme: dark; }
      *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
      body { background: #0b0a08; font-family: 'Inter', -apple-system, sans-serif; }
      @keyframes spin { to { transform: rotate(360deg); } }

      .invite-page {
        min-height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
        background:
          radial-gradient(60% 50% at 50% 0%, rgba(6,182,212,0.12), transparent 70%),
          #0b0a08;
        padding: 24px;
      }
      .invite-card {
        width: 100%;
        max-width: 440px;
        background: rgba(255,255,255,0.04);
        border: 1px solid rgba(255,255,255,0.08);
        border-radius: 20px;
        padding: 40px 32px;
        text-align: center;
        backdrop-filter: blur(20px);
      }
      .invite-icon {
        width: 56px; height: 56px;
        border-radius: 16px;
        display: flex; align-items: center; justify-content: center;
        margin: 0 auto 20px;
        background: rgba(6,182,212,0.12);
        color: #22d3ee;
      }
      .invite-card h1 {
        color: #F5F1E8;
        font-size: 22px;
        font-weight: 600;
        margin-bottom: 12px;
      }
      .invite-sub {
        color: rgba(245,241,232,0.62);
        font-size: 14px;
        line-height: 1.6;
        margin-bottom: 24px;
      }
      .invite-error { color: #f87171; }
      .invite-actions { display: flex; gap: 10px; justify-content: center; flex-wrap: wrap; }

      .btn-primary {
        display: inline-flex; align-items: center; justify-content: center;
        padding: 11px 22px;
        border-radius: 10px;
        border: none;
        background: linear-gradient(135deg, #06b6d4, #0891b2);
        color: #04202a;
        font-weight: 600;
        font-size: 14px;
        text-decoration: none;
        cursor: pointer;
        transition: transform .15s ease, box-shadow .15s ease;
      }
      .btn-primary:hover { transform: translateY(-1px); box-shadow: 0 8px 20px rgba(6,182,212,0.28); }

      .btn-ghost {
        display: inline-flex; align-items: center; justify-content: center;
        padding: 11px 22px;
        border-radius: 10px;
        border: 1px solid rgba(255,255,255,0.14);
        background: transparent;
        color: #F5F1E8;
        font-weight: 500;
        font-size: 14px;
        text-decoration: none;
        cursor: pointer;
        transition: background .15s ease;
      }
      .btn-ghost:hover { background: rgba(255,255,255,0.06); }

      .mini-spinner {
        width: 28px; height: 28px;
        border: 3px solid rgba(6,182,212,0.25);
        border-top-color: #06b6d4;
        border-radius: 50%;
        margin: 0 auto;
        animation: spin .8s linear infinite;
      }
    `}</style>
  )
}
