const registerWindowIpc = require('../ipc/window')
const registerBadgeIpc = require('../ipc/badge')
const registerNotificationsIpc = require('../ipc/notifications')
const { registerDownloadsIpc } = require('../ipc/downloads')
const { registerAppNotificationsIpc } = require('../ipc/appNotifications')
const { registerWeatherIpc } = require('../ipc/weather')
const registerAutoLaunchIpc = require('../ipc/autoLaunch')
const registerApiIpc = require('../ipc/api')
const { registerOAuthIpc } = require('../ipc/oauth')
const registerProxyIpc = require('../ipc/proxy')
const registerUpdaterIpc = require('../ipc/updater')
const registerSoundIpc = require('../ipc/sound')
const registerVpnIpc = require('../ipc/vpn')
const registerScreenshotIpc = require('../ipc/screenshot')
const registerExtensionsIpc = require('../ipc/extensions')
const { registerLockBackgroundIpc } = require('../ipc/lockBackground')
const { registerAssistantIpc } = require('../ipc/assistant')
const registerVaultIpc = require('../ipc/vault')
const registerPasswordManagerIpc = require('../ipc/passwordManager')
const registerTabManagerIpc = require('../ipc/tabManager')
const registerVisitorStatsIpc = require('../ipc/visitorStats')
const registerShortcutsIpc = require('../ipc/shortcuts')

function registerIpc({ getMainWindow, showMainWindow, updateTrayMenu, isQuittingRef }) {
    registerWindowIpc({ getMainWindow, isQuittingRef })
    registerBadgeIpc({ getMainWindow, updateTrayMenu })
    registerNotificationsIpc({ getMainWindow, showMainWindow })
    registerDownloadsIpc({ getMainWindow })
    registerAppNotificationsIpc({ getMainWindow })
    registerWeatherIpc()
    registerAutoLaunchIpc()
    registerApiIpc()
    registerOAuthIpc({ getMainWindow })
    registerProxyIpc()
    registerUpdaterIpc({ getMainWindow, isQuittingRef })
    registerSoundIpc()
    registerVpnIpc({ getMainWindow })
    registerScreenshotIpc({ getMainWindow })
    registerExtensionsIpc()
    registerLockBackgroundIpc({ getMainWindow })
    registerAssistantIpc({ getMainWindow })
    registerVaultIpc()
    registerPasswordManagerIpc({ getMainWindow })
    registerTabManagerIpc()
    registerVisitorStatsIpc()
    registerShortcutsIpc()
}

module.exports = registerIpc